protected/modules/admin/controllers/GoodController.php
<?php

class GoodController extends AdminController {


    public function actionIndex()
    {
        $model = $this->createSearchModel('Good');
        $provider = $model->search();
        $provider->pagination = array(
            'pageSize' => $this->getStoredParam('feedbackPerPage', 10),
        );
        $this->render('index', array(
            'model' => $model,
            'provider' => $provider,
        ));
    }

    public function actionCreate()
    {
        $model = new Good('create');
        $model->user_id= User::getCurrentUser()->id;
        if ($this->saveModel($model)) {
            $this->redirect(array('index'));
        }
        $this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionUpdate($id)
    {
        $model = $this->loadModel($id, 'Good');

        if ($this->saveModel($model)) {
            $this->redirect(array('index'));
        }
        $this->render('update', array(
            'model' => $model,
        ));

    }

    public function actionDelete($id)
    {
        $model = $this->loadModel($id, 'Good');
        $model->delete();
        if(!isset($_GET['ajax'])) {
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
    }
    public function actionGetGoodById()
    {
        if(Yii::app()->request->isAjaxRequest)
        {
            if(isset($_POST['Good']['id']))
            {
                $id = $_POST['Good']['id'];
                $currentGood = Good::model()->findByPk($id);
                echo CJSON::encode($currentGood);
				// echo json_encode($currentGood);
            }
        }
    }
    public  function actionGoodSupply()
    {
        $good = new Good();
        $good->setScenario('supply');
        if(isset($_POST['Good']))
        {
            $id = $_POST['Good']['id'];
            $good = Good::model()->findByPk($id);
            $good->attributes = $_POST['Good'];
            if($good->validate())
            {
                $good->update();
            }
        }
        $listGoods = Good::getListGood();
        $this->render('goodSupply',array(
            'listGoods'=>$listGoods,
            'good'=>$good, 
        ));
    }
//     необходимо  знать количество  каждого товара на складе 
    public function actionSaleOfGoods()
    {
        $good = new Good('update');
        $listGoods = Good::getListGood();
        if(isset($_POST['Good']))
        {
            $id = $_POST['Good']['id'];
            $good = $good->findByPk($id);
            $good->attributes = $_POST['Good'];
            if($good->validate())
            {
                $good->amount -= $good->numberSaledGoods;
                $good->update();
            }
        }
        $this->render('saleOfGoods',array(
            'good'=>$good,
            'listGoods'=>$listGoods,
        ));
        
    }

//    стоит   тут добавить  еще некоторые  действия  
    public function filters()
    {
        return array(
            'accessControl',
            'postOnly + delete',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions' => array('index'),
                'roles' => array('view_goods'),
            ),
            array('allow',
                'actions' => array('update'),
                'roles' => array('update_goods'),
            ),
            array('allow',
                'actions' => array('delete'),
                'roles' => array('delete_goods'),
            ),
            array('allow',
                'actions' => array('create'),
                'roles' => array('create_goods'),
            ),
            array('allow',
                'actions' => array('saleOfGoods'),
                'roles' => array('sale_Of_Goods'),
            ),
            array('allow',
                'actions' => array('goodSupply'),
                'roles' => array('good_supply'),
            ),
            array('allow',
                'actions' => array('getGoodById'),
                'roles' => array('get_Good_By_Id'),
            ),
            array('deny'),
        );
    }

}

protected/modules/admin/views/good/GoodController.php
<?php

class ClientController extends AdminController
{
    public function actionIndex()
    {
        $model = $this->createSearchModel('Client');
        $model->unsetAttributes();

        $dataProvider = $model->search();
        $dataProvider->pagination = array(
            'pageSize'=>10,
        );

        $this->render('index', array(
            'model' => $model,
            'dataProvider' => $dataProvider,
        ));
    }
    public function  actionView($id){
        $clientModel = Client::model()->findByPk($id);
        $this->render('view',array('client'=>$clientModel));
    }
    public function  actionUpdate($id)
    {
       $clientModel = Client::model()->findByPk($id);
        if(isset($_POST['Client']))
        {
            $clientModel->attributes = $_POST['Client'];
            if($clientModel->validate()){
                $clientModel->save(false);
                $this->redirect($this->createUrl('client/index'));
            }
        }
        $this->render('update',array('client'=>$clientModel));
    }
    public function  actionDelete($id)
    {
        Client::model()->deleteByPk($id);
    }
    public function  actionExportClients()
    {
        Yii::import('application.extensions.ExportXLS.ExportXLS');
        $headerColumns = array();
        foreach (Client::model()->getAttributes() as $key=>$value){
            $headerColumns[]=$key;
        }
        $filename = 'Clients.xls';
        $xls = new ExportXLS($filename);
        $xls->addHeader($headerColumns);
        $clients = Client::model()->findAll();
        foreach ($clients as $client){
            $tmp = array_values($client->attributes);
            $xls->addRow($tmp);
        }
        $xls->sendFile(); 
    }
    public function filters()
    {
        return array(
            'accessControl',
            'postOnly + delete',
        );
    }
}

protected/modules/admin/views/good/_form.php
<div class="form-content">


    <?php $form=$this->beginWidget('ActiveForm', array(
        'id' => 'goods-form',
        'htmlOptions' => array(
            'class'=>'form-horizontal',
        ),
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
            'afterValidate' => 'js:function(f,d,e) {
				if (e) $("html, body").animate({scrollTop: $("#goods-form").offset().top - 50}, 1000);
				return true;
			}',
        ),
    )); ?>

    <?php echo $form->errorSummary($model, null, null, array('class' => 'alert alert-danger')); ?>

    <div class="form-group">
        <?php echo $form->labelEx($model, 'name', array('class'=>'col-sm-3 control-label')); ?>
        <div class="col-sm-9">
            <?php echo $form->textField($model, 'name', array(
                'class' => 'form-control',
            )); ?>
            <?php echo $form->error($model, 'name', array('class'=>'help-inline')); ?>
        </div>
    </div>


    <div class="form-group">
        <?php echo $form->labelEx($model, 'description', array('class'=>'col-sm-3 control-label')); ?>
        <div class="col-sm-9">
            <?php echo $form->textField($model, 'description', array(
                'class' => 'form-control',
            )); ?>
            <?php echo $form->error($model, 'description', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $form->labelEx($model, 'price', array('class'=>'col-sm-3 control-label')); ?>
        <div class="col-sm-9">
            <?php echo $form->textField($model, 'price', array(
                'class' => 'form-control',
            )); ?>
            <?php echo $form->error($model, 'price', array('class'=>'help-inline')); ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $form->labelEx($model, 'amount', array('class'=>'col-sm-3 control-label')); ?>
        <div class="col-sm-9">
            <?php echo $form->textField($model, 'amount', array(
                'class' => 'form-control',
            )); ?>
            <?php echo $form->error($model, 'amount', array('class'=>'help-inline')); ?>
        </div>
    </div>





    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?php echo CHtml::submitButton(Yii::t('admin.crud', $model->isNewRecord ? 'Create' : 'Update'), array('class'=>'btn btn-primary')); ?>
        </div>
    </div>

    <?php $this->endWidget(); ?>
</div>

protected/modules/admin/views/good/create.php
<?php

$this->pageHeading = Yii::t('admin.crud', 'Add Goods');

$this->breadcrumbs = array(
    Yii::t('admin.crud', 'FeedbackStatus') => Yii::app()->user->checkAccess('view_goods') ? array('index') : false,
    Yii::t('admin.crud', 'Add'),
);

$this->menu = array(
    array(
        'label' => '<i class="glyphicon glyphicon-wrench"></i> ' . Yii::t('admin.crud', 'Manage Goods'),
        'url' => array('index'),
        'visible' => Yii::app()->user->checkAccess('view_goods'),
    ),
);

?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->pageHeading; ?></h3>
    </div>
    <div class="panel-body">
        <?php $this->renderPartial('_form', array(
            'model' => $model,
        )); ?>
    </div>
</div>

protected/modules/admin/views/good/goodSupply.php
<div class="form-content">
    <?php echo CHtml::beginForm();?>
    <div class="form-group">
        <div class="col-sm-9">
            <?php echo CHtml::errorSummary($good);?>
        </div>
    </div>
    <div class="form-group">     
        <?php echo CHtml::activeLabel($good,'name',array('class'=>'col-sm-3 control-label'));?>
	<div class="col-sm-9">
            <?php echo CHtml::activeDropDownList($good, 'id', $listGoods, array('onChange'=>'changeGoodId(this.value)'));?>        
	</div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good,'amount',array('class'=>'col-sm-3 control-label'));?>
        <div class="col-sm-9">
            <?php echo CHtml::activeTextField($good,'amount');?>    
        </div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good,'user_id',array('class'=>'col-sm-3 control-label'));?>
        <div class="col-sm-9">
            <?php echo CHtml::activeTextField($good,'user_id',array('class'=>'col-sm-3','readonly'=>'readonly'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good,'price',array('class'=>'col-sm-3 control-label'));?>
        <div class="col-sm-9">
            <?php echo CHtml::activeTextField($good,'price',array('class'=>'col-sm-3'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good,'purchase_price',array('class'=>'col-sm-3 control-label'));?>
        <div class="col-sm-9">
            <?php echo CHtml::activeTextField($good,'purchase_price',array('class'=>'col-sm-3 control-label'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good,'date_added',array('class'=>'col-sm-3 control-label'));?>
        <div class="col-sm-9">
            <?php 
               $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'created',
                    'model' => $good,
                    'attribute' => 'date_added',
                    'language' => 'ru',
                    'options' => array(
                        'showAnim' => 'fold',
                        'dateFormat' => 'yy-mm-dd',
                    ),
                ));?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9"> 
            <?php echo CHtml::submitButton('Добавить поступление',array('class'=>'btn btn-primary'))?>
        </div>
    </div>
    <?php echo CHtml::endForm();?>
</div>
<script type="text/javascript">
function changeGoodId(data)
{
    var url = "<?php  echo Yii::app()->controller->createAbsoluteUrl('/admin/good/getGoodById');?>";
    $.post(
            url,
            {"Good":{'id':data}},
            function(data)
            {
               var  parseData = JSON.parse(data);  
               $('#Good_amount').val(parseData.amount);
               $('#Good_user_id').val(parseData.user_id);
               $('#Good_price').val(parseData.price);
               $('#Good_purchase_price').val(parseData.purchase_price);
                console.log(parseData);   
            }
            );
    console.log(data);
    console.log(url);
}
</script>

protected/modules/admin/views/good/index.php
<?php

$this->pageHeading = Yii::t('admin.crud', 'Manage Goods');

$this->breadcrumbs = array(
    Yii::t('admin.crud', 'Good'),
);

$this->menu = array(
    array(
        'label' => '<i class="glyphicon glyphicon-plus"></i> ' . Yii::t('admin.crud', 'Add Goods'),
        'url' => array('create'),
        'visible' => Yii::app()->user->checkAccess('create_goods'),
    ),

);

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->pageHeading; ?></h3>
    </div>
    <?php $this->widget('GridView', array(
        'id' => 'feedback-grid',
        'dataProvider' => $provider,
        'columns' => array(
            'id',
            'name',
            'description',
            'price',
            'amount',
            'img',
            array(
                'class' => 'ButtonColumn',
                'deleteConfirmation' => 'Вы уверены, что хотите удалить этот статус?',
                'template' =>
                (Yii::app()->user->checkAccess('update_goods') ? '{update}' : '').
                (Yii::app()->user->checkAccess('delete_goods') ? '{delete}' : ''),
            ),

        ),
    )); ?>
</div>

protected/modules/admin/views/good/saleOfGoods.php
<div class="form-content">
    <?php echo CHtml::beginForm();?>
    <div class="form-group">
        <div  class="col-sm-9">
            <?php echo CHtml::errorSummary($good);?>
        </div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good,'name',array('class'=>'col-sm-3 control-label'));?>
        <div  class="col-sm-9">
            <?php echo CHtml::activeDropDownList($good, 'id', $listGoods, array('onChange'=>'changeGoodId(this.value)'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good, 'amount',array('class'=>'col-sm-3 control-label'));?>
        <div  class="col-sm-9">
            <?php echo CHtml::activeTextField($good,'amount',array('readonly'=>'readonly'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo CHtml::activeLabel($good,'numberSaledGoods',array('class'=>'col-sm-3 control-lable'));?>
        <div  class="col-sm-9">
            <?php echo CHtml::activeTextField($good,'numberSaledGoods');?>
        </div>
    </div>
    <div class="form-group">
        <div  class="col-sm-9">
            <?php echo CHtml::submitButton('На сервер'); ?>
        </div>
    </div>
    <?php echo CHtml::endForm();?>
</div>
<script type="text/javascript">
function changeGoodId(data)
{
    var url = "<?php  echo Yii::app()->controller->createAbsoluteUrl('/admin/good/getGoodById');?>";
    $.post(
            url,
            {"Good":{'id':data}},
            function(data)
            {
                
               var  parseData = JSON.parse(data);  
               $('#Good_amount').val(parseData.amount);
               console.log(parseData);
               $('#Good_user_id').val(parseData.user_id);
               $('#Good_price').val(parseData.price);
               $('#Good_purchase_price').val(parseData.purchase_price);
                console.log(parseData);   
            }
            );
    console.log(data);
    console.log(url);
}
</script>

protected/modules/admin/views/good/update.php
<?php

$this->pageHeading = Yii::t('admin.crud', 'Update Goods');

$this->breadcrumbs = array(
    Yii::t('admin.crud', 'Good') => Yii::app()->user->checkAccess('view_goods') ? array('index') : false,
    Yii::t('admin.crud', 'Update'),
);

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->pageHeading; ?></h3>
    </div>
    <div class="panel-body">
        <?php $this->renderPartial('_form', array(
            'model' => $model,
        )); ?>
    </div>
</div>